# Generated by Django 3.1 on 2020-09-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200822_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=False, max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
